config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'vivocameras/new'
  get 'vivocameras/show'
  get 'vivocameras/edit'
  get 'vivocamera_userinputs/new'
  get 'vivocamera_userinputs/show'
  get 'vivocamera_userinputs/edit'
  patch 'vivocamera_userinputs/update'
  
  get 'inputcamera' =>'vivocameras#new'
  get 'cameraindex' =>'vivocameras#index'
  get 'userinputs' =>'vivocamera_userinputs#new'
  patch 'userinputs_update' => 'vivocamera_userinputs#update'
  
  resources :vivocameras do
    resources :userinputs, :controller => 'vivocamera_userinputs'
  end

end

app/models/internal.rb
class Internal < ActiveRecord::Base
end

app/models/userinput.rb
class Userinput < ActiveRecord::Base
end

app/models/userinputsdf.rb
class Userinputsdf < ActiveRecord::Base
end

app/models/vivocamera.rb
class Vivocamera < ActiveRecord::Base
  has_many :userinputs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/userinputs_controller.rb
class UserinputsController < ApplicationController
  def new
     @userinput = Userinput.new
  end
  
  def index
  @userinputs = Userinput.all
  end

  def create
    @userinput = Userinput.new(userinput_params)
     @userinput.save
      flash[:success] = "IP camera property successful created!"
      redirect_to :action => :index
    
  end
  
  def show
    @userinput = Userinput.find(params[:id])
  end

  private

   def userinput_params
     params.require(:userinput).permit(:property, :vivocamera_id)
   end
  
  
  
  
  
end

app/controllers/vivocamera_userinputs_controller.rb
class VivocameraUserinputsController < ApplicationController
   require 'mymodule'
   require 'vivocommon'
   before_action :find_vivocamera , only: [:new,:create, :show]
   STATUS = [['Active', 'active'], ['In Active', 'inactive']]
  def new
     @userinput = @vivocamera.userinputs.build
  end
  
  def show
    
    @userinputs = @vivocamera.userinputs
  end
  
  
  def index
  @userinputs = @vivocamera.userinputs
  end

  def create
     
     @userinput = @vivocamera.userinputs.build(userinput_params)
     
     #@my_obj = ::Mymodule.new(@userinput)
     @my_obj2 = ::Vivocommon.new(@userinput)
     
     #im_awesome
     #gen_config
     
     #@target  = "../../vivoconfig/vivoconfig"
     #@content = "hellohello"
     
     #@f = File.open('/home/ubuntu/workspace/vivo/vivoconfig/vivoconfig.xml', "w+")
     #@f.write(@content)   
     #@f.close()
     #File.open('/home/ubuntu/workspace/vivo/vivoconfig.xml', 'w') do |f2|  
        # use "\n" for two lines of text  
     #   f2.puts "Created by Satish\nThank God!"  
     #end  
     
    if @userinput.save
       flash[:success] = "IP camera property successful created!"
    redirect_to  cameraindex_path
    else
    render :action => :new
    end
  end
  
  def edit
     @vivocamera = Vivocamera.find( params[:vivocamera_id] )
    @userinput = @vivocamera.userinputs.find(params[:vivocamera_id])
  end

  def update
       @vivocamera = Vivocamera.find( params[:vivocamera_id] )
     @userinput = @vivocamera.userinputs.find( params[:vivocamera_id] )

     @userinput.update_attributes(userinput_params)
      flash[:success] = "IPcamera properties updated!"
      redirect_to cameraindex_path
    

  end


  private
  
  
  def gen_config
      gen_capability
      gen_ddns
      
  end
  
  def gen_audioin
      
  end
  
  def gen_audioout
      
  end
  
  def gen_capability
     @f = File.open('/home/ubuntu/workspace/vivo/vivoconfig/config_capability.xml', "w+")
     @content='<?xml version="1.0" standalone="yes"?>' + "\n"
     @content+='<root>' + "\n"
     @content+='<capability>' + "\n"
     
     @content+='<bootuptime>'
     @content+=@userinput.bootuptim
     @content+='</bootuptime>'+ "\n"
     
     @f.write(@content)   
     @f.close()      
  end
  
  def gen_ddns
     @f = File.open('/home/ubuntu/workspace/vivo/vivoconfig/config_ddns.xml', "w+")
     @content='config_ddns.xml'
     @f.write(@content)   
     @f.close()     
  end
  
  def gen_disk

  end
  
  def gen_dst
      
  end
  
  def gen_eptz
      
  end
  
  def gen_exposurewindows
  
  end
  
  
  
  
  
  
  
  
  

  def find_vivocamera
    @vivocamera = Vivocamera.find( params[:vivocamera_id] )
  end

  
  
  
  
   def userinput_params
     params.require(:userinput).permit(:bootuptim,
                                       :ir,
                                       :extir,
                                       :npir,
                                       :ndi,
                                       :nvi )
   end
  
  
end

app/controllers/vivocameras_controller.rb
class VivocamerasController < ApplicationController


 def show
  @vivocamera=Vivocamera.find(params[:id])
 end

 def new
   @vivocamera=Vivocamera.new
   @vivocameras=Vivocamera.all
 end

 def index
  @vivocameras=Vivocamera.all
 end


  def create
    @vivocamera = Vivocamera.new(vivocamera_params)
     @vivocamera.save
      flash[:success] = "IP camera successful created!"
       
       
     redirect_to :controller => :vivocamera_userinputs, :action => :new, :vivocamera_id => @vivocamera.id
  
  end

 def edit
   @vivocamera = Vivocamera.find(params[:vivocamera_id])
 end

 def update
   @vivocamera = Vivocamera.find(params[:id])
   
   @vivocamera.update_attributes(vivocamera_params)
      flash[:success] = "IPcamera name updated!"
      redirect_to cameraindex_path
   
 end
  

  private

    def vivocamera_params
      params.require(:vivocamera).permit(:name)
    end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camerasessions_helper.rb
module CamerasessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/userinputs_helper.rb
module UserinputsHelper
end

app/helpers/vivocamera_userinputs_helper.rb
module VivocameraUserinputsHelper
end

app/helpers/vivocameras_helper.rb
module VivocamerasHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Vivotek version0 software</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
     <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
    <div class="container">
       <div id="sub">
         
         <div class="input_camera">
         <h1>Create IP camera:</h1>
         <%= link_to "Create an IP camera", inputcamera_path, class: "btn btn-primary" %>
           
         </div>
         
         <div class="input_camera">
           <h1> List of all Vivotek cameras:</h1>
         <%= link_to "Show all IP cameras", cameraindex_path, class: "btn btn-primary" %>
          </div>
         
         
       </div>
  
       <div id="main">
         <%= yield %>
       </div>
    
    </div>  
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<p> ViVo tek Home Page</p>
  

app/views/vivocamera_userinputs/edit.html.erb
<%= form_for @userinput , :url => userinputs_update_path(@vivocamera, @userinput,:vivocamera_id => @vivocamera.id) do |f| %>
  
  <br>
    <%= f.label :bootuptim, "bootuptim" %>
    <%= f.text_field :bootuptim %>
<br>
     <%= f.label :ir, "ir" %>
    <%= f.text_field :ir %>
  <br>  
     <%= f.label :extir, "extir" %>
    <%= f.text_field :extir %>
   <br> 
     <%= f.label :npir, "npir" %>
    <%= f.text_field :npir %>
   <br> 
     <%= f.label :ndi, "ndi" %>
    <%= f.text_field :ndi %>
  <br>
    <%= f.label :nvi, "nvi" %>
    <%= f.text_field :nvi %>
  <br>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <br>
<% end %>

app/views/vivocamera_userinputs/index.html.erb
<ul>
 

   <%  File.open("./log/internalinput.xml", "r").each_line do |line|  internaldata = line   %>

 <%=   internaldata %>
 
  <% end   %>
 
  
  
  
</ul>

 



<% @userinputs.each do |userinput| %>
<% filename= "vivocamera-"+userinput.vivocamera.name  %>
<% my_file = File.new("./log/"+filename+".xml","w")  %>
<% my_file.write "<root>"+ "\n" %>
<% my_file.write "        <capability>"+ "\n" %>
<% my_file.write "                <api>"+ "\n" %>
<% my_file.write "                        <httpversion>0300a</httpversion>"+ "\n" %>
<% my_file.write "                </api>"+ "\n" %>
<% my_file.write "                <bootuptime>"+userinput.bootuptim+"</bootuptime>"+ "\n" %>
<% my_file.write "                <ir>"+userinput.ir+"</ir>"+ "\n" %>
<% my_file.write "                <extir>"+userinput.extir+"</extir>"+ "\n" %>
<% my_file.write "                <npir>"+userinput.npir+"</npir>"+ "\n" %>
<% my_file.write "                <ndi>"+userinput.ndi+"</ndi>"+ "\n" %>
<% my_file.write "                <nvi>"+userinput.nvi+"</nvi>"+ "\n" %>


<% my_file.close %>

<% end %>

app/views/vivocamera_userinputs/show.html.erb
 <% @userinputs.each do |userinput| %>
 IPcamera name:<%= userinput.vivocamera.name %><br />
< root ><br />
< capability ><br />
               < api ><br />
       < httpversion >0300a< httpversion ><br />
              < /api ><br />
        < bootuptime ><%= userinput.bootuptim %>< /bootuptime ><br />
                < ir ><%= userinput.ir %>< /ir ><br />
             < extir ><%= userinput.extir %>< /extir ><br />
              < npir ><%= userinput.npir %>< /npir > <br />
               < ndi ><%= userinput.ndi %>< /ndi ><br />
               < nvi ><%= userinput.nvi %>< /nvi ><br />

<%= link_to 'edit camera property', vivocamera_userinputs_edit_path(@vivocamera, @userinputs, :vivocamera_id => @vivocamera.id)    %>

<% end %>

app/views/vivocameras/edit.html.erb
  <%= tabs %>
   <%= form_for(@vivocamera) do |f| %>
      <%= f.label :name ,"IP camera name" %>
      <%= f.text_field :name %>

      <%= f.submit "Save IP camera name", class: "btn btn-primary" %>
    <% end %>
    
    <hr />

app/views/vivocameras/index.html.erb
List of all Vivotek cameras:
 
<ul>
<% @vivocameras.each do |vivocamera| %>
	<li>
	 Vivo IPcamera name: <%= vivocamera.name %>
	  <%= link_to 'show', :controller => :vivocamera_userinputs, :action => :show ,:vivocamera_id => vivocamera.id   %>
	  <%= link_to 'edit camera name', :controller => :vivocameras, :action => :edit , :vivocamera_id => vivocamera.id  %>
	 
	</li>
<% end %>

  

app/views/vivocameras/new.html.erb
   <%= form_for(@vivocamera) do |f| %>
      <%= f.label :name ,"IP camera name" %>
      <%= f.text_field :name %>

      <%= f.submit "Create an IP camera name", class: "btn btn-primary" %>
    <% end %>

app/views/vivocameras/show.html.erb
 <p>攝影機名稱show: <%= @vivocamera.name %>